SELECT CITY FROM STATION WHERE CITY LIKE 'a%';
SELECT CITY FROM STATION WHERE CITY LIKE 'e%';
SELECT CITY FROM STATION WHERE CITY LIKE 'i%';
SELECT CITY FROM STATION WHERE CITY LIKE 'o%';
SELECT CITY FROM STATION WHERE CITY LIKE 'u%';
